title: "Documentation de la Machine That Draw"
description: "Documentation du projet — Makerspace Amiens 2025-2026"
baseurl: ""
url: ""

theme: just-the-docs

aux_links:
  "GitHub":
    - "https://github.com/Makerspace-Amiens-2025-26/MachineThatDraws-Groupe06"

aux_links_new_tab: true
search_enabled: true
heading_anchors: true

footer_content: "Machine That Draw &mdash; Groupe 06 &mdash; Makerspace Amiens 2025-2026"

plugins:
  - jekyll-seo-tag

exclude:
  - premiers-pas/
