title: Doc Projet
description: Documentation du projet
favicon_ico: "/images/image.ico"

# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Thème
theme: bulma-clean-theme
baseurl: "/MachineThatDraws-Groupe06"
url: "https://Makerspace-Amiens-2025-2026.github.io"
