title: "Doc Projet Groupe 06"
description: "Documentation du projet Machine That Draws"

# CONFIGURATION DE L'ADRESSE (Mise à jour suite au transfert)
remote_theme: "Makerspace-Amiens/bulma-clean-theme"
baseurl: "/MachineThatDraws-Groupe06"
url: "https://makerspace-amiens-2025-26.github.io"

# NE RIEN TOUCHER CI-DESSOUS
plugins:
  - jekyll-remote-theme
