name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false
          working-directory: ${{env.working-directory}}
      - name: Install gems
        run: bundle install
        working-directory: ${{env.working-directory}}
      - name: Build with Jekyll
        run: bundle exec jekyll build
        working-directory: ${{env.working-directory}}